### ISSUE TITLE
Why no `Imports.hs` for the `base` category?

### ISSUE THREAD

**Issue by kindaro** [haskell-game/tiny-games-hs#11]
It seems unfair that people that choose to compete in the `default` category get to use more packages and also get more lines!

It is kind of hard to say in what sense exactly this is unfair, since there is no formal competition between categories. But I can try to make this precise like so:

1. Any game fit for `base` also fits for `default` — it is vacuously true that it uses only default packages.
2. I can therefore move any game built for `base` to `default` and get to move imports to `Imports.hs` and gain more lines. This is a clear advantage in the terms of taking the most out of the system.
3. Therefore, if I am working on an idea for a game, my only incentive to keep it in `base` is to reduce competition. This puts everyone who chooses this category in bad light.

Another reason is that `base` has a lot of modules. It is hard to take advantage of them without using `Imports.hs`. In `default` you get to import any number of modules, but in `base` only a small amount. This seems like an arbitrary handicap to the category `base` itself.

So, this is unfair not to any individual competitor, but to the whole category `base`, for the above two reasons.

The above notwithstanding, I think it would be bad sport to change the rules now. Maybe the next competition can ameliorate this?

**Comment by simonmichael** [comment]
Restriction fosters creativity, and these four levels of restriction can produce different results. Also, each provides a different challenge in how to use the haskell tools to get a runnable game. I encourage you to try them all ! 

Also, it's research; we learn from trying stuff. It turns out that the default GHC packages aren't very useful  for making games, and we have no entries in that category yet; I doubt we'll use that one next time.

**Comment by kindaro** [comment]
I hear you!
