### ISSUE TITLE
Question: is separate Imports.hs file considered "worse" for judging purposes?

### ISSUE THREAD

**Issue by gergoerdi** [haskell-game/tiny-games-hs#41]

**Comment by simonmichael** [comment]
IMHO: Slightly, all other things being equal.. because having to employ multiple files is less satisfying as we attempt to match the power of BASIC. The extra file hurts runnability, eg (running the program from another directory becomes hard).

Considering the verbosity and need of imports in Haskell, I added this option to allow us to meet the 10 lines challenge. So if it's needed, I wouldn't worry about it too much. Alternately one could upload a batteries-included games lib to hackage and use that. Surprisingly though, people have being doing just fine with one or two imports.

**Comment by simonmichael** [comment]
Another way we can look at it: allowing a custom prelude is our way of matching the very wide range of "BASIC"s allowed by the BASIC 10Liner contest.

**Comment by simonmichael** [comment]
Answered, hopefully, so I'll close this.
